#!/bin/bash
# tpchtest

# Stop on errors
# set -e

# Sanity check command line options
usage() {
  printf "Note: you need to rebuild the pyverdict package (if some change is made to verdictdb) because it is used as the interface here \nUsage: $0 [presto] [filename] \n"
}

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

# Parse argument.  $1 is the first argument
case $1 in
  "presto")
    # set -x
    # echo "Error: database already exists"
    if [ -f $2 ]; then
      rm $2
    fi

    for i in `seq 1 20`;
    do
      echo "==================================================================="
      echo "Running Test #$i"
      scramble="_scramble.py"
      test_scramble="python py/tpch_q$i$scramble $2"
      eval $test_scramble
    done
    ;;

  *)
    usage
    exit 1
    ;;
esac
